import { ddLang } from './localize';

/**
 * Nette, leesbare namen voor entiteit-domeinen (device-types).
 * Engels is de standaard; Nederlands wordt gekozen op basis van de HA-taal.
 * Onbekende domeinen vallen terug op een "geprettificeerde" naam
 * (underscores → spaties, elk woord met hoofdletter).
 */
const DOMAIN_NAMES: Record<'en' | 'nl' | 'zh', Record<string, string>> = {
  en: {
    light: '灯光',
    switch: '开关',
    fan: '风扇',
    cover: '窗帘',
    lock: '锁',
    climate: '气候',
    media_player: '媒体播放器',
    camera: '摄像头',
    person: '人员',
    vacuum: '吸尘器',
    alarm_control_panel: '警报',
    binary_sensor: '二进制传感器',
    sensor: '传感器',
    energy: '能源',
    scene: '场景',
    event: '事件',
    script: '脚本',
    automation: '自动化',
    button: '按钮',
    number: '数值',
    select: '选择器',
    input_boolean: '切换',
    input_number: '数值输入',
    input_select: '选择输入',
    input_button: '按钮输入',
    input_text: '文本字段',
    water_heater: '热水器',
    humidifier: '加湿器',
    siren: '警报器',
    valve: '阀门',
    update: '更新',
    weather: '天气',
    sun: '太阳',
    device_tracker: '设备追踪',
    remote: '遥控器',
    image: '图片',
    todo: '待办事项',
    calendar: '日历',
    lawn_mower: '割草机',
    text: '文本字段',
    date: '日期',
    time: '时间',
    timer: '计时器',
  },
  nl: {
    light: 'Lampen',
    switch: 'Schakelaars',
    fan: 'Ventilatoren',
    cover: 'Zonwering',
    lock: 'Sloten',
    climate: 'Klimaat',
    media_player: 'Mediaspelers',
    camera: "Camera's",
    person: 'Personen',
    vacuum: 'Stofzuigers',
    alarm_control_panel: 'Alarm',
    binary_sensor: 'Binaire sensoren',
    sensor: 'Sensoren',
    energy: 'Energie',
    scene: 'Scènes',
    event: 'Gebeurtenissen',
    script: 'Scripts',
    automation: 'Automatiseringen',
    button: 'Knoppen',
    number: 'Nummers',
    select: 'Keuzelijsten',
    input_boolean: 'Schakelaars',
    input_number: 'Nummers',
    input_select: 'Keuzelijsten',
    input_button: 'Knoppen',
    input_text: 'Tekstvelden',
    water_heater: 'Boilers',
    humidifier: 'Luchtbevochtigers',
    siren: 'Sirenes',
    valve: 'Kleppen',
    update: 'Updates',
    weather: 'Weer',
    sun: 'Zon',
    device_tracker: 'Apparaatlocatie',
    remote: 'Afstandsbedieningen',
    image: 'Afbeeldingen',
    todo: 'Takenlijsten',
    calendar: "Agenda's",
    lawn_mower: 'Grasmaaiers',
    text: 'Tekstvelden',
    date: 'Datums',
    time: 'Tijden',
    timer: 'Timers',
  },
  zh: {
    light: '灯光',
    switch: '开关',
    fan: '风扇',
    cover: '窗帘',
    lock: '锁',
    climate: '气候',
    media_player: '媒体播放器',
    camera: '摄像头',
    person: '人员',
    vacuum: '吸尘器',
    alarm_control_panel: '警报',
    binary_sensor: '二进制传感器',
    sensor: '传感器',
    energy: '能源',
    scene: '场景',
    event: '事件',
    script: '脚本',
    automation: '自动化',
    button: '按钮',
    number: '数值',
    select: '选择器',
    input_boolean: '切换',
    input_number: '数值输入',
    input_select: '选择输入',
    input_button: '按钮输入',
    input_text: '文本字段',
    water_heater: '热水器',
    humidifier: '加湿器',
    siren: '警报器',
    valve: '阀门',
    update: '更新',
    weather: '天气',
    sun: '太阳',
    device_tracker: '设备追踪',
    remote: '遥控器',
    image: '图片',
    todo: '待办事项',
    calendar: '日历',
    lawn_mower: '割草机',
    text: '文本字段',
    date: '日期',
    time: '时间',
    timer: '计时器',
  },
};

/**
 * Leesbare namen voor (binary_)sensor device-classes, zodat een motion-sensor
 * als "Motion" verschijnt i.p.v. "Binary sensors".
 */
const DEVICE_CLASS_NAMES: Record<'en' | 'nl' | 'zh', Record<string, string>> = {
  en: {
    motion: 'Motion',
    moving: 'Motion',
    occupancy: 'Occupancy',
    presence: 'Presence',
    door: 'Doors',
    garage_door: 'Garage doors',
    window: 'Windows',
    opening: 'Openings',
    smoke: 'Smoke',
    gas: 'Gas',
    carbon_monoxide: 'Carbon monoxide',
    moisture: 'Moisture',
    safety: 'Safety',
    tamper: 'Tamper',
    vibration: 'Vibration',
    sound: 'Sound',
    lock: 'Locks',
    battery: 'Battery',
    battery_charging: 'Charging',
    connectivity: 'Connectivity',
    power: 'Power',
    plug: 'Plugs',
    problem: 'Problems',
    heat: 'Heat',
    cold: 'Cold',
    light: 'Light',
    running: 'Running',
    update: 'Updates',
    door_lock: 'Locks',
  },
  nl: {
    motion: 'Beweging',
    moving: 'Beweging',
    occupancy: 'Aanwezigheid',
    presence: 'Aanwezigheid',
    door: 'Deuren',
    garage_door: 'Garagedeuren',
    window: 'Ramen',
    opening: 'Openingen',
    smoke: 'Rook',
    gas: 'Gas',
    carbon_monoxide: 'Koolmonoxide',
    moisture: 'Vocht',
    safety: 'Veiligheid',
    tamper: 'Sabotage',
    vibration: 'Trilling',
    sound: 'Geluid',
    lock: 'Sloten',
    battery: 'Batterij',
    battery_charging: 'Opladen',
    connectivity: 'Verbinding',
    power: 'Stroom',
    plug: 'Stekkers',
    problem: 'Problemen',
    heat: 'Hitte',
    cold: 'Kou',
    light: 'Licht',
    running: 'Actief',
    update: 'Updates',
    door_lock: 'Sloten',
  },
  zh: {
    motion: '运动',
    moving: '运动',
    occupancy: '占用',
    presence: '存在',
    door: '门',
    garage_door: '车库门',
    window: '窗户',
    opening: '开口',
    smoke: '烟雾',
    gas: '气体',
    carbon_monoxide: '一氧化碳',
    moisture: '湿度',
    safety: '安全',
    tamper: '篡改',
    vibration: '振动',
    sound: '声音',
    lock: '锁',
    battery: '电池',
    battery_charging: '充电中',
    connectivity: '连接',
    power: '电源',
    plug: '插头',
    problem: '问题',
    heat: '热量',
    cold: '寒冷',
    light: '光线',
    running: '运行中',
    update: '更新',
    door_lock: '门锁',
  },
};

/** Leesbare, gelokaliseerde naam voor een device-class. */
export function getDeviceClassName(hass: any, deviceClass: string): string {
  const lang = ddLang(hass);
  return (
    DEVICE_CLASS_NAMES[lang]?.[deviceClass] ??
    DEVICE_CLASS_NAMES.en[deviceClass] ??
    prettifyDomain(deviceClass)
  );
}

/** Maak van een ruw domein ("binary_sensor") een leesbare naam ("Binary Sensor"). */
export function prettifyDomain(domain: string): string {
  return domain
    .split('_')
    .map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : w))
    .join(' ');
}

/** Leesbare, gelokaliseerde naam voor een domein. */
export function getDomainName(hass: any, domain: string): string {
  const lang = ddLang(hass);
  return (
    DOMAIN_NAMES[lang]?.[domain] ??
    DOMAIN_NAMES.en[domain] ??
    prettifyDomain(domain)
  );
}
